#pragma once

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM 200

#define RGBLIGHT_HUE_STEP 252
#define RGBLIGHT_SAT_STEP 55
#define RGBLIGHT_VAL_STEP 50
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LED_COUNT 56
#define SPLIT_LAYER_STATE_ENABLE
